### ISSUE TITLE
401K should say SIMPLE IRA

### ISSUE THREAD

**Issue by jlampel** [CGCookie/handbook#2]
> **401K Retirement Plan**
> CG Cookie offers a matching 401k retirement plan, where we will match up to 3%.

https://github.com/cgcookie/handbook/blob/master/benefits.md#401k-retirement-plan

As far as I can tell from the linked Basecamp documents, the only plan offered is a SIMPLE IRA. A 401K match does not currently appear to be an option. This does make a difference as the annual contribution limit of a 401K is $6,000 higher than the limit of the SIMPLE IRA.

**Comment by carter2422** [comment]
Good catch @jlampel! Fixing.
